[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
#linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-Dwarnings",
    "-Ctarget-cpu=cortex-a53",
    #"-Ctarget-feature=+aes",
    #"-Ctarget-feature=+v8a,+strict-align", # https://github.com/rust-lang/rust/issues/66897
]

